// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ducECpb1-OlsdGAM3DHUOmPhoeuRpz8',
    appId: '1:779941257565:web:e823f474e17d299c1b88b4',
    messagingSenderId: '779941257565',
    projectId: 'spotify-clone-asdf123',
    authDomain: 'spotify-clone-asdf123.firebaseapp.com',
    storageBucket: 'spotify-clone-asdf123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKbyCckhVgBOwESJaoeLX5_bkhi991n30',
    appId: '1:779941257565:android:6bd8c0f30840e16f1b88b4',
    messagingSenderId: '779941257565',
    projectId: 'spotify-clone-asdf123',
    storageBucket: 'spotify-clone-asdf123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEm1aUQjuIFoipIvnesHlWsJbcEzPL2Qk',
    appId: '1:779941257565:ios:dc3f20623f933d811b88b4',
    messagingSenderId: '779941257565',
    projectId: 'spotify-clone-asdf123',
    storageBucket: 'spotify-clone-asdf123.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
}
